# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataArchive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 588)
        MainWindow.setMaximumSize(QtCore.QSize(816, 588))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #536976, stop:1 #292E49);\n"
"border-radius:5px;")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(697, -7, 121, 61))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.exit_btn = QtWidgets.QPushButton(self.frame)
        self.exit_btn.setGeometry(QtCore.QRect(66, 10, 51, 41))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(209, 0, 0);\n"
"border-radius:5px;\n"
"}")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo/icons8-close-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(30, 30))
        self.exit_btn.setObjectName("exit_btn")
        self.minimize_btn = QtWidgets.QPushButton(self.frame)
        self.minimize_btn.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.minimize_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(118, 118, 118);\n"
"border-radius:5px;\n"
"}")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photo/icons8-horizontal-line-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setIconSize(QtCore.QSize(30, 30))
        self.minimize_btn.setObjectName("minimize_btn")
        self.connection_btn = QtWidgets.QPushButton(self.centralwidget)
        self.connection_btn.setGeometry(QtCore.QRect(1, 3, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.connection_btn.setFont(font)
        self.connection_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connection_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"}\n"
"")
        self.connection_btn.setIconSize(QtCore.QSize(30, 30))
        self.connection_btn.setObjectName("connection_btn")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 50, 691, 541))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label_39 = QtWidgets.QLabel(self.home)
        self.label_39.setGeometry(QtCore.QRect(60, 80, 551, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(72)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_42 = QtWidgets.QLabel(self.home)
        self.label_42.setGeometry(QtCore.QRect(50, 260, 551, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(72)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.up_time_label = QtWidgets.QLabel(self.home)
        self.up_time_label.setGeometry(QtCore.QRect(520, 0, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setItalic(False)
        self.up_time_label.setFont(font)
        self.up_time_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.up_time_label.setText("")
        self.up_time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.up_time_label.setObjectName("up_time_label")
        self.up_date_label = QtWidgets.QLabel(self.home)
        self.up_date_label.setGeometry(QtCore.QRect(0, 0, 141, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setItalic(False)
        self.up_date_label.setFont(font)
        self.up_date_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.up_date_label.setText("")
        self.up_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.up_date_label.setObjectName("up_date_label")
        self.stackedWidget.addWidget(self.home)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.label_2 = QtWidgets.QLabel(self.profile)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.profile)
        self.label_7.setGeometry(QtCore.QRect(40, 180, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.profile)
        self.label_6.setGeometry(QtCore.QRect(30, 300, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.profile)
        self.label_9.setGeometry(QtCore.QRect(61, 240, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.profile)
        self.label_5.setGeometry(QtCore.QRect(190, 0, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setItalic(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border-bottom:1px solid black;\n"
"border-radius:0px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.profile_username = QtWidgets.QLineEdit(self.profile)
        self.profile_username.setGeometry(QtCore.QRect(140, 130, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_username.setFont(font)
        self.profile_username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.profile_username.setObjectName("profile_username")
        self.profile_fullname = QtWidgets.QLineEdit(self.profile)
        self.profile_fullname.setGeometry(QtCore.QRect(140, 190, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_fullname.setFont(font)
        self.profile_fullname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.profile_fullname.setObjectName("profile_fullname")
        self.profile_email = QtWidgets.QLineEdit(self.profile)
        self.profile_email.setGeometry(QtCore.QRect(140, 250, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_email.setFont(font)
        self.profile_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.profile_email.setObjectName("profile_email")
        self.profile_password = QtWidgets.QLineEdit(self.profile)
        self.profile_password.setGeometry(QtCore.QRect(140, 310, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_password.setFont(font)
        self.profile_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.profile_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.profile_password.setObjectName("profile_password")
        self.profile_type = QtWidgets.QLineEdit(self.profile)
        self.profile_type.setGeometry(QtCore.QRect(140, 370, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_type.setFont(font)
        self.profile_type.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.profile_type.setObjectName("profile_type")
        self.label_8 = QtWidgets.QLabel(self.profile)
        self.label_8.setGeometry(QtCore.QRect(60, 360, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.profile_edit = QtWidgets.QPushButton(self.profile)
        self.profile_edit.setGeometry(QtCore.QRect(280, 480, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_edit.setFont(font)
        self.profile_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profile_edit.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("photo/outline_edit_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_edit.setIcon(icon2)
        self.profile_edit.setIconSize(QtCore.QSize(30, 30))
        self.profile_edit.setObjectName("profile_edit")
        self.profile_submit = QtWidgets.QPushButton(self.profile)
        self.profile_submit.setGeometry(QtCore.QRect(420, 480, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_submit.setFont(font)
        self.profile_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profile_submit.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("photo/outline_done_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_submit.setIcon(icon3)
        self.profile_submit.setIconSize(QtCore.QSize(30, 30))
        self.profile_submit.setObjectName("profile_submit")
        self.profile_refresh = QtWidgets.QPushButton(self.profile)
        self.profile_refresh.setGeometry(QtCore.QRect(140, 480, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_refresh.setFont(font)
        self.profile_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profile_refresh.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("photo/outline_refresh_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_refresh.setIcon(icon4)
        self.profile_refresh.setIconSize(QtCore.QSize(30, 30))
        self.profile_refresh.setObjectName("profile_refresh")
        self.profile_state = QtWidgets.QLabel(self.profile)
        self.profile_state.setGeometry(QtCore.QRect(150, 420, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.profile_state.setFont(font)
        self.profile_state.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.profile_state.setText("")
        self.profile_state.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_state.setObjectName("profile_state")
        self.stackedWidget.addWidget(self.profile)
        self.setting = QtWidgets.QWidget()
        self.setting.setObjectName("setting")
        self.api_btn = QtWidgets.QPushButton(self.setting)
        self.api_btn.setGeometry(QtCore.QRect(560, 20, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.api_btn.setFont(font)
        self.api_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.api_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("photo/outline_api_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.api_btn.setIcon(icon5)
        self.api_btn.setIconSize(QtCore.QSize(30, 30))
        self.api_btn.setObjectName("api_btn")
        self.urls_frame = QtWidgets.QFrame(self.setting)
        self.urls_frame.setGeometry(QtCore.QRect(0, 10, 551, 521))
        self.urls_frame.setStyleSheet("background-color: none;")
        self.urls_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.urls_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.urls_frame.setObjectName("urls_frame")
        self.label_15 = QtWidgets.QLabel(self.urls_frame)
        self.label_15.setGeometry(QtCore.QRect(-10, 240, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.setting_profile_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_profile_url.setGeometry(QtCore.QRect(140, 90, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_profile_url.setFont(font)
        self.setting_profile_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_profile_url.setObjectName("setting_profile_url")
        self.label_13 = QtWidgets.QLabel(self.urls_frame)
        self.label_13.setGeometry(QtCore.QRect(0, 199, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.urls_frame)
        self.label_16.setGeometry(QtCore.QRect(-10, 279, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.setting_del_data_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_del_data_url.setGeometry(QtCore.QRect(140, 290, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_del_data_url.setFont(font)
        self.setting_del_data_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_del_data_url.setObjectName("setting_del_data_url")
        self.label_10 = QtWidgets.QLabel(self.urls_frame)
        self.label_10.setGeometry(QtCore.QRect(-10, 0, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_18 = QtWidgets.QLabel(self.urls_frame)
        self.label_18.setGeometry(QtCore.QRect(0, 320, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.setting_checkbox_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_checkbox_url.setGeometry(QtCore.QRect(140, 170, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_checkbox_url.setFont(font)
        self.setting_checkbox_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_checkbox_url.setObjectName("setting_checkbox_url")
        self.setting_send_data_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_send_data_url.setGeometry(QtCore.QRect(140, 210, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_send_data_url.setFont(font)
        self.setting_send_data_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_send_data_url.setObjectName("setting_send_data_url")
        self.setting_register_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_register_url.setGeometry(QtCore.QRect(140, 50, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_register_url.setFont(font)
        self.setting_register_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_register_url.setObjectName("setting_register_url")
        self.setting_get_data_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_get_data_url.setGeometry(QtCore.QRect(140, 250, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_get_data_url.setFont(font)
        self.setting_get_data_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_get_data_url.setObjectName("setting_get_data_url")
        self.setting_login_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_login_url.setGeometry(QtCore.QRect(140, 10, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_login_url.setFont(font)
        self.setting_login_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_login_url.setObjectName("setting_login_url")
        self.label_12 = QtWidgets.QLabel(self.urls_frame)
        self.label_12.setGeometry(QtCore.QRect(10, 39, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.setting_users_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_users_url.setGeometry(QtCore.QRect(140, 330, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_users_url.setFont(font)
        self.setting_users_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_users_url.setObjectName("setting_users_url")
        self.label_14 = QtWidgets.QLabel(self.urls_frame)
        self.label_14.setGeometry(QtCore.QRect(12, 80, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_11 = QtWidgets.QLabel(self.urls_frame)
        self.label_11.setGeometry(QtCore.QRect(0, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_32 = QtWidgets.QLabel(self.urls_frame)
        self.label_32.setGeometry(QtCore.QRect(0, 360, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.setting_insert_feedback_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_insert_feedback_url.setGeometry(QtCore.QRect(140, 370, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_insert_feedback_url.setFont(font)
        self.setting_insert_feedback_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_insert_feedback_url.setObjectName("setting_insert_feedback_url")
        self.setting_admin_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_admin_url.setGeometry(QtCore.QRect(140, 490, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_admin_url.setFont(font)
        self.setting_admin_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_admin_url.setObjectName("setting_admin_url")
        self.label_38 = QtWidgets.QLabel(self.urls_frame)
        self.label_38.setGeometry(QtCore.QRect(0, 480, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.setting_get_profile_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_get_profile_url.setGeometry(QtCore.QRect(140, 132, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_get_profile_url.setFont(font)
        self.setting_get_profile_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_get_profile_url.setObjectName("setting_get_profile_url")
        self.label_17 = QtWidgets.QLabel(self.urls_frame)
        self.label_17.setGeometry(QtCore.QRect(0, 120, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_43 = QtWidgets.QLabel(self.urls_frame)
        self.label_43.setGeometry(QtCore.QRect(0, 400, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.setting_get_feedback_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_get_feedback_url.setGeometry(QtCore.QRect(140, 410, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_get_feedback_url.setFont(font)
        self.setting_get_feedback_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_get_feedback_url.setObjectName("setting_get_feedback_url")
        self.label_44 = QtWidgets.QLabel(self.urls_frame)
        self.label_44.setGeometry(QtCore.QRect(0, 440, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.setting_del_feedback_url = QtWidgets.QLineEdit(self.urls_frame)
        self.setting_del_feedback_url.setGeometry(QtCore.QRect(140, 450, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_del_feedback_url.setFont(font)
        self.setting_del_feedback_url.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.setting_del_feedback_url.setObjectName("setting_del_feedback_url")
        self.feedback_chart_btn = QtWidgets.QPushButton(self.setting)
        self.feedback_chart_btn.setGeometry(QtCore.QRect(560, 80, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_chart_btn.setFont(font)
        self.feedback_chart_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback_chart_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("photo/outline_table_chart_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedback_chart_btn.setIcon(icon6)
        self.feedback_chart_btn.setIconSize(QtCore.QSize(30, 30))
        self.feedback_chart_btn.setObjectName("feedback_chart_btn")
        self.admin_btn = QtWidgets.QPushButton(self.setting)
        self.admin_btn.setGeometry(QtCore.QRect(560, 140, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.admin_btn.setFont(font)
        self.admin_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.admin_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("photo/outline_admin_panel_settings_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.admin_btn.setIcon(icon7)
        self.admin_btn.setIconSize(QtCore.QSize(30, 30))
        self.admin_btn.setObjectName("admin_btn")
        self.stackedWidget.addWidget(self.setting)
        self.send_data = QtWidgets.QWidget()
        self.send_data.setObjectName("send_data")
        self.label_19 = QtWidgets.QLabel(self.send_data)
        self.label_19.setGeometry(QtCore.QRect(10, 9, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.send_data_title = QtWidgets.QLineEdit(self.send_data)
        self.send_data_title.setGeometry(QtCore.QRect(120, 20, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_title.setFont(font)
        self.send_data_title.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_title.setObjectName("send_data_title")
        self.label_20 = QtWidgets.QLabel(self.send_data)
        self.label_20.setGeometry(QtCore.QRect(10, 59, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.send_data_fullname = QtWidgets.QLineEdit(self.send_data)
        self.send_data_fullname.setGeometry(QtCore.QRect(120, 70, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_fullname.setFont(font)
        self.send_data_fullname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_fullname.setObjectName("send_data_fullname")
        self.label_21 = QtWidgets.QLabel(self.send_data)
        self.label_21.setGeometry(QtCore.QRect(20, 210, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.send_data_phone = QtWidgets.QLineEdit(self.send_data)
        self.send_data_phone.setGeometry(QtCore.QRect(120, 120, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_phone.setFont(font)
        self.send_data_phone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_phone.setInputMethodHints(QtCore.Qt.ImhNone)
        self.send_data_phone.setObjectName("send_data_phone")
        self.label_22 = QtWidgets.QLabel(self.send_data)
        self.label_22.setGeometry(QtCore.QRect(10, 110, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.send_data_company = QtWidgets.QLineEdit(self.send_data)
        self.send_data_company.setGeometry(QtCore.QRect(120, 170, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_company.setFont(font)
        self.send_data_company.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_company.setObjectName("send_data_company")
        self.label_23 = QtWidgets.QLabel(self.send_data)
        self.label_23.setGeometry(QtCore.QRect(10, 160, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.send_data_price = QtWidgets.QLineEdit(self.send_data)
        self.send_data_price.setGeometry(QtCore.QRect(120, 220, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_price.setFont(font)
        self.send_data_price.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_price.setObjectName("send_data_price")
        self.label_24 = QtWidgets.QLabel(self.send_data)
        self.label_24.setGeometry(QtCore.QRect(30, 310, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.send_data_combobox_state = QtWidgets.QComboBox(self.send_data)
        self.send_data_combobox_state.setGeometry(QtCore.QRect(121, 320, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_combobox_state.setFont(font)
        self.send_data_combobox_state.setStyleSheet("background-color: none;")
        self.send_data_combobox_state.setObjectName("send_data_combobox_state")
        self.send_data_combobox_state.addItem("")
        self.send_data_combobox_state.addItem("")
        self.send_data_combobox_state.addItem("")
        self.label_25 = QtWidgets.QLabel(self.send_data)
        self.label_25.setGeometry(QtCore.QRect(290, 310, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.send_data_combobox_pay = QtWidgets.QComboBox(self.send_data)
        self.send_data_combobox_pay.setGeometry(QtCore.QRect(360, 320, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_combobox_pay.setFont(font)
        self.send_data_combobox_pay.setStyleSheet("background-color: none;")
        self.send_data_combobox_pay.setObjectName("send_data_combobox_pay")
        self.send_data_combobox_pay.addItem("")
        self.send_data_combobox_pay.addItem("")
        self.send_data_combobox_pay.addItem("")
        self.send_data_date = QtWidgets.QLineEdit(self.send_data)
        self.send_data_date.setGeometry(QtCore.QRect(120, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_date.setFont(font)
        self.send_data_date.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_date.setInputMethodHints(QtCore.Qt.ImhNone)
        self.send_data_date.setObjectName("send_data_date")
        self.label_27 = QtWidgets.QLabel(self.send_data)
        self.label_27.setGeometry(QtCore.QRect(20, 260, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.send_data_time = QtWidgets.QLineEdit(self.send_data)
        self.send_data_time.setGeometry(QtCore.QRect(360, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_time.setFont(font)
        self.send_data_time.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_time.setInputMethodHints(QtCore.Qt.ImhNone)
        self.send_data_time.setObjectName("send_data_time")
        self.label_28 = QtWidgets.QLabel(self.send_data)
        self.label_28.setGeometry(QtCore.QRect(270, 260, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.send_data_combobox_price = QtWidgets.QComboBox(self.send_data)
        self.send_data_combobox_price.setGeometry(QtCore.QRect(380, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_combobox_price.setFont(font)
        self.send_data_combobox_price.setStyleSheet("background-color: none;")
        self.send_data_combobox_price.setObjectName("send_data_combobox_price")
        self.send_data_combobox_price.addItem("")
        self.send_data_combobox_price.addItem("")
        self.send_data_combobox_price.addItem("")
        self.send_data_combobox_price.addItem("")
        self.send_data_combobox_price.addItem("")
        self.send_data_frame_tracking = QtWidgets.QFrame(self.send_data)
        self.send_data_frame_tracking.setGeometry(QtCore.QRect(9, 360, 541, 51))
        self.send_data_frame_tracking.setStyleSheet("background-color: none;")
        self.send_data_frame_tracking.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.send_data_frame_tracking.setFrameShadow(QtWidgets.QFrame.Raised)
        self.send_data_frame_tracking.setObjectName("send_data_frame_tracking")
        self.label_26 = QtWidgets.QLabel(self.send_data_frame_tracking)
        self.label_26.setGeometry(QtCore.QRect(1, 0, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.send_data_tracking_code = QtWidgets.QLineEdit(self.send_data_frame_tracking)
        self.send_data_tracking_code.setGeometry(QtCore.QRect(140, 10, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_tracking_code.setFont(font)
        self.send_data_tracking_code.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.send_data_tracking_code.setObjectName("send_data_tracking_code")
        self.send_data_submit_btn = QtWidgets.QPushButton(self.send_data)
        self.send_data_submit_btn.setGeometry(QtCore.QRect(410, 480, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_submit_btn.setFont(font)
        self.send_data_submit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_data_submit_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.send_data_submit_btn.setIcon(icon3)
        self.send_data_submit_btn.setIconSize(QtCore.QSize(30, 30))
        self.send_data_submit_btn.setObjectName("send_data_submit_btn")
        self.send_data_clear_btn = QtWidgets.QPushButton(self.send_data)
        self.send_data_clear_btn.setGeometry(QtCore.QRect(270, 480, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_clear_btn.setFont(font)
        self.send_data_clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_data_clear_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("photo/outline_clear_all_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_data_clear_btn.setIcon(icon8)
        self.send_data_clear_btn.setIconSize(QtCore.QSize(30, 30))
        self.send_data_clear_btn.setObjectName("send_data_clear_btn")
        self.send_data_edit_btn = QtWidgets.QPushButton(self.send_data)
        self.send_data_edit_btn.setGeometry(QtCore.QRect(130, 480, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_edit_btn.setFont(font)
        self.send_data_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_data_edit_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.send_data_edit_btn.setIcon(icon2)
        self.send_data_edit_btn.setIconSize(QtCore.QSize(30, 30))
        self.send_data_edit_btn.setObjectName("send_data_edit_btn")
        self.send_data_state_label = QtWidgets.QLabel(self.send_data)
        self.send_data_state_label.setGeometry(QtCore.QRect(120, 410, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.send_data_state_label.setFont(font)
        self.send_data_state_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.send_data_state_label.setText("")
        self.send_data_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.send_data_state_label.setObjectName("send_data_state_label")
        self.stackedWidget.addWidget(self.send_data)
        self.get_data = QtWidgets.QWidget()
        self.get_data.setObjectName("get_data")
        self.tableWidget_get_data = QtWidgets.QTableWidget(self.get_data)
        self.tableWidget_get_data.setGeometry(QtCore.QRect(5, 1, 679, 401))
        self.tableWidget_get_data.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_get_data.setObjectName("tableWidget_get_data")
        self.tableWidget_get_data.setColumnCount(12)
        self.tableWidget_get_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_get_data.setHorizontalHeaderItem(11, item)
        self.get_data_state_label = QtWidgets.QLabel(self.get_data)
        self.get_data_state_label.setGeometry(QtCore.QRect(350, 410, 331, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.get_data_state_label.setFont(font)
        self.get_data_state_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.get_data_state_label.setText("")
        self.get_data_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.get_data_state_label.setObjectName("get_data_state_label")
        self.get_data_your_user_btn = QtWidgets.QPushButton(self.get_data)
        self.get_data_your_user_btn.setGeometry(QtCore.QRect(70, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.get_data_your_user_btn.setFont(font)
        self.get_data_your_user_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_data_your_user_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("photo/baseline_person_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.get_data_your_user_btn.setIcon(icon9)
        self.get_data_your_user_btn.setIconSize(QtCore.QSize(30, 30))
        self.get_data_your_user_btn.setObjectName("get_data_your_user_btn")
        self.get_data_all_data_btn = QtWidgets.QPushButton(self.get_data)
        self.get_data_all_data_btn.setGeometry(QtCore.QRect(210, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.get_data_all_data_btn.setFont(font)
        self.get_data_all_data_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_data_all_data_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("photo/baseline_all_inbox_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.get_data_all_data_btn.setIcon(icon10)
        self.get_data_all_data_btn.setIconSize(QtCore.QSize(30, 30))
        self.get_data_all_data_btn.setObjectName("get_data_all_data_btn")
        self.label_29 = QtWidgets.QLabel(self.get_data)
        self.label_29.setGeometry(QtCore.QRect(7, 413, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.get_data)
        self.label_30.setGeometry(QtCore.QRect(-10, 470, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.get_data_id_lineedit = QtWidgets.QLineEdit(self.get_data)
        self.get_data_id_lineedit.setGeometry(QtCore.QRect(50, 482, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.get_data_id_lineedit.setFont(font)
        self.get_data_id_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.get_data_id_lineedit.setObjectName("get_data_id_lineedit")
        self.frame_4 = QtWidgets.QFrame(self.get_data)
        self.frame_4.setGeometry(QtCore.QRect(200, 460, 281, 71))
        self.frame_4.setStyleSheet("background-color:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.get_data_refresh_btn = QtWidgets.QPushButton(self.frame_4)
        self.get_data_refresh_btn.setGeometry(QtCore.QRect(150, 16, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.get_data_refresh_btn.setFont(font)
        self.get_data_refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_data_refresh_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.get_data_refresh_btn.setIcon(icon4)
        self.get_data_refresh_btn.setIconSize(QtCore.QSize(30, 30))
        self.get_data_refresh_btn.setObjectName("get_data_refresh_btn")
        self.get_data_delete_btn = QtWidgets.QPushButton(self.frame_4)
        self.get_data_delete_btn.setGeometry(QtCore.QRect(10, 16, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.get_data_delete_btn.setFont(font)
        self.get_data_delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_data_delete_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("photo/outline_delete_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.get_data_delete_btn.setIcon(icon11)
        self.get_data_delete_btn.setIconSize(QtCore.QSize(30, 30))
        self.get_data_delete_btn.setObjectName("get_data_delete_btn")
        self.stackedWidget.addWidget(self.get_data)
        self.users = QtWidgets.QWidget()
        self.users.setObjectName("users")
        self.tableWidget_users = QtWidgets.QTableWidget(self.users)
        self.tableWidget_users.setGeometry(QtCore.QRect(5, 1, 679, 401))
        self.tableWidget_users.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_users.setObjectName("tableWidget_users")
        self.tableWidget_users.setColumnCount(6)
        self.tableWidget_users.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_users.setHorizontalHeaderItem(5, item)
        self.users_state_label = QtWidgets.QLabel(self.users)
        self.users_state_label.setGeometry(QtCore.QRect(120, 410, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.users_state_label.setFont(font)
        self.users_state_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.users_state_label.setText("")
        self.users_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.users_state_label.setObjectName("users_state_label")
        self.users_id_lineedit = QtWidgets.QLineEdit(self.users)
        self.users_id_lineedit.setGeometry(QtCore.QRect(50, 482, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.users_id_lineedit.setFont(font)
        self.users_id_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.users_id_lineedit.setObjectName("users_id_lineedit")
        self.label_31 = QtWidgets.QLabel(self.users)
        self.label_31.setGeometry(QtCore.QRect(-10, 470, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.frame_5 = QtWidgets.QFrame(self.users)
        self.frame_5.setGeometry(QtCore.QRect(200, 460, 281, 71))
        self.frame_5.setStyleSheet("background-color:none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.users_refresh_btn = QtWidgets.QPushButton(self.frame_5)
        self.users_refresh_btn.setGeometry(QtCore.QRect(150, 16, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.users_refresh_btn.setFont(font)
        self.users_refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.users_refresh_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.users_refresh_btn.setIcon(icon4)
        self.users_refresh_btn.setIconSize(QtCore.QSize(30, 30))
        self.users_refresh_btn.setObjectName("users_refresh_btn")
        self.users_delete_btn = QtWidgets.QPushButton(self.frame_5)
        self.users_delete_btn.setGeometry(QtCore.QRect(10, 16, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.users_delete_btn.setFont(font)
        self.users_delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.users_delete_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.users_delete_btn.setIcon(icon11)
        self.users_delete_btn.setIconSize(QtCore.QSize(30, 30))
        self.users_delete_btn.setObjectName("users_delete_btn")
        self.stackedWidget.addWidget(self.users)
        self.feedback = QtWidgets.QWidget()
        self.feedback.setObjectName("feedback")
        self.label_33 = QtWidgets.QLabel(self.feedback)
        self.label_33.setGeometry(QtCore.QRect(40, 148, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.feedback_title = QtWidgets.QLineEdit(self.feedback)
        self.feedback_title.setGeometry(QtCore.QRect(130, 160, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_title.setFont(font)
        self.feedback_title.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.feedback_title.setObjectName("feedback_title")
        self.label_34 = QtWidgets.QLabel(self.feedback)
        self.label_34.setGeometry(QtCore.QRect(20, 100, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.feedback_username = QtWidgets.QLineEdit(self.feedback)
        self.feedback_username.setGeometry(QtCore.QRect(130, 112, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_username.setFont(font)
        self.feedback_username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.feedback_username.setObjectName("feedback_username")
        self.label_35 = QtWidgets.QLabel(self.feedback)
        self.label_35.setGeometry(QtCore.QRect(180, 10, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(36)
        font.setItalic(True)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border-bottom:1px solid black;\n"
"border-radius:0px;")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.feedback_subject = QtWidgets.QLineEdit(self.feedback)
        self.feedback_subject.setGeometry(QtCore.QRect(130, 210, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_subject.setFont(font)
        self.feedback_subject.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.feedback_subject.setText("")
        self.feedback_subject.setObjectName("feedback_subject")
        self.label_36 = QtWidgets.QLabel(self.feedback)
        self.label_36.setGeometry(QtCore.QRect(27, 198, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.feedback)
        self.label_37.setGeometry(QtCore.QRect(20, 244, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.feedback_send_btn = QtWidgets.QPushButton(self.feedback)
        self.feedback_send_btn.setGeometry(QtCore.QRect(370, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_send_btn.setFont(font)
        self.feedback_send_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback_send_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("photo/outline_send_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedback_send_btn.setIcon(icon12)
        self.feedback_send_btn.setIconSize(QtCore.QSize(30, 30))
        self.feedback_send_btn.setObjectName("feedback_send_btn")
        self.feedback_clear_btn = QtWidgets.QPushButton(self.feedback)
        self.feedback_clear_btn.setGeometry(QtCore.QRect(170, 490, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_clear_btn.setFont(font)
        self.feedback_clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback_clear_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.feedback_clear_btn.setIcon(icon8)
        self.feedback_clear_btn.setIconSize(QtCore.QSize(30, 30))
        self.feedback_clear_btn.setObjectName("feedback_clear_btn")
        self.feedback_state_label = QtWidgets.QLabel(self.feedback)
        self.feedback_state_label.setGeometry(QtCore.QRect(120, 440, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.feedback_state_label.setFont(font)
        self.feedback_state_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.feedback_state_label.setText("")
        self.feedback_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.feedback_state_label.setObjectName("feedback_state_label")
        self.feedback_TextEdit = QtWidgets.QTextEdit(self.feedback)
        self.feedback_TextEdit.setGeometry(QtCore.QRect(130, 260, 401, 161))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_TextEdit.setFont(font)
        self.feedback_TextEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.feedback_TextEdit.setObjectName("feedback_TextEdit")
        self.stackedWidget.addWidget(self.feedback)
        self.feedback_chart = QtWidgets.QWidget()
        self.feedback_chart.setObjectName("feedback_chart")
        self.tableWidget_feedback = QtWidgets.QTableWidget(self.feedback_chart)
        self.tableWidget_feedback.setGeometry(QtCore.QRect(5, 60, 679, 401))
        self.tableWidget_feedback.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_feedback.setObjectName("tableWidget_feedback")
        self.tableWidget_feedback.setColumnCount(5)
        self.tableWidget_feedback.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_feedback.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_feedback.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_feedback.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_feedback.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_feedback.setHorizontalHeaderItem(4, item)
        self.feedbacks_id_lineedit = QtWidgets.QLineEdit(self.feedback_chart)
        self.feedbacks_id_lineedit.setGeometry(QtCore.QRect(50, 482, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedbacks_id_lineedit.setFont(font)
        self.feedbacks_id_lineedit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.feedbacks_id_lineedit.setObjectName("feedbacks_id_lineedit")
        self.label_40 = QtWidgets.QLabel(self.feedback_chart)
        self.label_40.setGeometry(QtCore.QRect(-10, 470, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.feedbacks_state_label = QtWidgets.QLabel(self.feedback_chart)
        self.feedbacks_state_label.setGeometry(QtCore.QRect(460, 470, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.feedbacks_state_label.setFont(font)
        self.feedbacks_state_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.feedbacks_state_label.setText("")
        self.feedbacks_state_label.setAlignment(QtCore.Qt.AlignCenter)
        self.feedbacks_state_label.setObjectName("feedbacks_state_label")
        self.frame_6 = QtWidgets.QFrame(self.feedback_chart)
        self.frame_6.setGeometry(QtCore.QRect(190, 460, 271, 71))
        self.frame_6.setStyleSheet("background-color:none;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.feedbacks_refresh_btn = QtWidgets.QPushButton(self.frame_6)
        self.feedbacks_refresh_btn.setGeometry(QtCore.QRect(140, 16, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedbacks_refresh_btn.setFont(font)
        self.feedbacks_refresh_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedbacks_refresh_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.feedbacks_refresh_btn.setIcon(icon4)
        self.feedbacks_refresh_btn.setIconSize(QtCore.QSize(30, 30))
        self.feedbacks_refresh_btn.setObjectName("feedbacks_refresh_btn")
        self.feedbacks_delete_btn = QtWidgets.QPushButton(self.frame_6)
        self.feedbacks_delete_btn.setGeometry(QtCore.QRect(10, 16, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedbacks_delete_btn.setFont(font)
        self.feedbacks_delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedbacks_delete_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.feedbacks_delete_btn.setIcon(icon11)
        self.feedbacks_delete_btn.setIconSize(QtCore.QSize(30, 30))
        self.feedbacks_delete_btn.setObjectName("feedbacks_delete_btn")
        self.feedback_state_label_2 = QtWidgets.QLabel(self.frame_6)
        self.feedback_state_label_2.setGeometry(QtCore.QRect(270, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.feedback_state_label_2.setFont(font)
        self.feedback_state_label_2.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.feedback_state_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.feedback_state_label_2.setObjectName("feedback_state_label_2")
        self.label_41 = QtWidgets.QLabel(self.feedback_chart)
        self.label_41.setGeometry(QtCore.QRect(240, 0, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setItalic(True)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);\n"
"border-bottom:1px solid black;\n"
"border-radius:0px;")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.setting_back_btn = QtWidgets.QPushButton(self.feedback_chart)
        self.setting_back_btn.setGeometry(QtCore.QRect(6, 10, 51, 41))
        self.setting_back_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_back_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(118, 118, 118);\n"
"border-radius:5px;\n"
"}")
        self.setting_back_btn.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("photo/outline_arrow_back_ios_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_back_btn.setIcon(icon13)
        self.setting_back_btn.setIconSize(QtCore.QSize(30, 30))
        self.setting_back_btn.setObjectName("setting_back_btn")
        self.stackedWidget.addWidget(self.feedback_chart)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 40, 121, 541))
        self.frame_2.setStyleSheet("background-color: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.setting_btn = QtWidgets.QPushButton(self.frame_2)
        self.setting_btn.setGeometry(QtCore.QRect(-10, 110, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.setting_btn.setFont(font)
        self.setting_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("photo/outline_settings_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon14)
        self.setting_btn.setIconSize(QtCore.QSize(30, 30))
        self.setting_btn.setObjectName("setting_btn")
        self.profile_btn = QtWidgets.QPushButton(self.frame_2)
        self.profile_btn.setGeometry(QtCore.QRect(-10, 60, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.profile_btn.setFont(font)
        self.profile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profile_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("photo/icons8-user-profile-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_btn.setIcon(icon15)
        self.profile_btn.setIconSize(QtCore.QSize(30, 30))
        self.profile_btn.setObjectName("profile_btn")
        self.send_data_btn = QtWidgets.QPushButton(self.frame_2)
        self.send_data_btn.setGeometry(QtCore.QRect(-10, 160, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.send_data_btn.setFont(font)
        self.send_data_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_data_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("photo/icons8-outgoing-data-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_data_btn.setIcon(icon16)
        self.send_data_btn.setIconSize(QtCore.QSize(30, 30))
        self.send_data_btn.setObjectName("send_data_btn")
        self.get_data_btn = QtWidgets.QPushButton(self.frame_2)
        self.get_data_btn.setGeometry(QtCore.QRect(-10, 210, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.get_data_btn.setFont(font)
        self.get_data_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_data_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("photo/icons8-incoming-data-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.get_data_btn.setIcon(icon17)
        self.get_data_btn.setIconSize(QtCore.QSize(30, 30))
        self.get_data_btn.setObjectName("get_data_btn")
        self.feedback_btn = QtWidgets.QPushButton(self.frame_2)
        self.feedback_btn.setGeometry(QtCore.QRect(-10, 310, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.feedback_btn.setFont(font)
        self.feedback_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("photo/outline_feedback_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedback_btn.setIcon(icon18)
        self.feedback_btn.setIconSize(QtCore.QSize(30, 30))
        self.feedback_btn.setObjectName("feedback_btn")
        self.users_btn = QtWidgets.QPushButton(self.frame_2)
        self.users_btn.setGeometry(QtCore.QRect(-10, 260, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.users_btn.setFont(font)
        self.users_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.users_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("photo/icons8-users-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.users_btn.setIcon(icon19)
        self.users_btn.setIconSize(QtCore.QSize(30, 30))
        self.users_btn.setObjectName("users_btn")
        self.log_out_btn = QtWidgets.QPushButton(self.frame_2)
        self.log_out_btn.setGeometry(QtCore.QRect(-10, 410, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.log_out_btn.setFont(font)
        self.log_out_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.log_out_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("photo/icons8-logout-58.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.log_out_btn.setIcon(icon20)
        self.log_out_btn.setIconSize(QtCore.QSize(30, 30))
        self.log_out_btn.setObjectName("log_out_btn")
        self.info_btn = QtWidgets.QPushButton(self.frame_2)
        self.info_btn.setGeometry(QtCore.QRect(-10, 360, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.info_btn.setFont(font)
        self.info_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.info_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("photo/outline_info_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_btn.setIcon(icon21)
        self.info_btn.setIconSize(QtCore.QSize(30, 30))
        self.info_btn.setObjectName("info_btn")
        self.home_btn = QtWidgets.QPushButton(self.frame_2)
        self.home_btn.setGeometry(QtCore.QRect(-10, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.home_btn.setFont(font)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("photo/outline_home_black_24dp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon22)
        self.home_btn.setIconSize(QtCore.QSize(30, 30))
        self.home_btn.setObjectName("home_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.exit_btn.clicked.connect(MainWindow.close)
        self.minimize_btn.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connection_btn.setText(_translate("MainWindow", "Connection"))
        self.label_39.setText(_translate("MainWindow", "Data Archive"))
        self.label_42.setText(_translate("MainWindow", "Welcome"))
        self.label_2.setText(_translate("MainWindow", "Username :"))
        self.label_7.setText(_translate("MainWindow", "Fullname :"))
        self.label_6.setText(_translate("MainWindow", "Password :"))
        self.label_9.setText(_translate("MainWindow", "Email :"))
        self.label_5.setText(_translate("MainWindow", "Profile"))
        self.profile_username.setPlaceholderText(_translate("MainWindow", "username"))
        self.profile_fullname.setPlaceholderText(_translate("MainWindow", "fullname"))
        self.profile_email.setPlaceholderText(_translate("MainWindow", "email"))
        self.profile_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.profile_type.setPlaceholderText(_translate("MainWindow", "type"))
        self.label_8.setText(_translate("MainWindow", "Type :"))
        self.profile_edit.setText(_translate("MainWindow", " Edit"))
        self.profile_submit.setText(_translate("MainWindow", "Submit"))
        self.profile_refresh.setText(_translate("MainWindow", "Refresh"))
        self.api_btn.setText(_translate("MainWindow", "API List"))
        self.label_15.setText(_translate("MainWindow", "Get data :"))
        self.setting_profile_url.setPlaceholderText(_translate("MainWindow", "edit profile api"))
        self.label_13.setText(_translate("MainWindow", "Send data :"))
        self.label_16.setText(_translate("MainWindow", "Delete data :"))
        self.setting_del_data_url.setPlaceholderText(_translate("MainWindow", "delete data api"))
        self.label_10.setText(_translate("MainWindow", "Login url :"))
        self.label_18.setText(_translate("MainWindow", "Users :"))
        self.setting_checkbox_url.setPlaceholderText(_translate("MainWindow", "checkbox api"))
        self.setting_send_data_url.setPlaceholderText(_translate("MainWindow", "send data api"))
        self.setting_register_url.setPlaceholderText(_translate("MainWindow", "register api"))
        self.setting_get_data_url.setPlaceholderText(_translate("MainWindow", "get data api"))
        self.setting_login_url.setPlaceholderText(_translate("MainWindow", "login api"))
        self.label_12.setText(_translate("MainWindow", "Register url :"))
        self.setting_users_url.setPlaceholderText(_translate("MainWindow", "users api"))
        self.label_14.setText(_translate("MainWindow", "Edit Profile :"))
        self.label_11.setText(_translate("MainWindow", "CheckBox :"))
        self.label_32.setText(_translate("MainWindow", "Cr-Feedback :"))
        self.setting_insert_feedback_url.setPlaceholderText(_translate("MainWindow", "insert feedback api"))
        self.setting_admin_url.setPlaceholderText(_translate("MainWindow", "admin url"))
        self.label_38.setText(_translate("MainWindow", "Admin url :"))
        self.setting_get_profile_url.setPlaceholderText(_translate("MainWindow", "get profile api"))
        self.label_17.setText(_translate("MainWindow", "Get profile :"))
        self.label_43.setText(_translate("MainWindow", "Gt-Feedback :"))
        self.setting_get_feedback_url.setPlaceholderText(_translate("MainWindow", "get feedback api"))
        self.label_44.setText(_translate("MainWindow", "Del-Feedback :"))
        self.setting_del_feedback_url.setPlaceholderText(_translate("MainWindow", "delete feedback url"))
        self.feedback_chart_btn.setText(_translate("MainWindow", "Feedbacks"))
        self.admin_btn.setText(_translate("MainWindow", " Admin"))
        self.label_19.setText(_translate("MainWindow", "Title :"))
        self.send_data_title.setPlaceholderText(_translate("MainWindow", "title"))
        self.label_20.setText(_translate("MainWindow", "Fullname :"))
        self.send_data_fullname.setPlaceholderText(_translate("MainWindow", "fullname"))
        self.label_21.setText(_translate("MainWindow", "Price :"))
        self.send_data_phone.setPlaceholderText(_translate("MainWindow", "phone"))
        self.label_22.setText(_translate("MainWindow", "Phone :"))
        self.send_data_company.setPlaceholderText(_translate("MainWindow", "company"))
        self.label_23.setText(_translate("MainWindow", "Company :"))
        self.send_data_price.setPlaceholderText(_translate("MainWindow", "price"))
        self.label_24.setText(_translate("MainWindow", "State :"))
        self.send_data_combobox_state.setItemText(0, _translate("MainWindow", "None"))
        self.send_data_combobox_state.setItemText(1, _translate("MainWindow", "Done"))
        self.send_data_combobox_state.setItemText(2, _translate("MainWindow", "In queue"))
        self.label_25.setText(_translate("MainWindow", "Pay :"))
        self.send_data_combobox_pay.setItemText(0, _translate("MainWindow", "None"))
        self.send_data_combobox_pay.setItemText(1, _translate("MainWindow", "Yes"))
        self.send_data_combobox_pay.setItemText(2, _translate("MainWindow", "No"))
        self.send_data_date.setPlaceholderText(_translate("MainWindow", "date"))
        self.label_27.setText(_translate("MainWindow", "Date :"))
        self.send_data_time.setPlaceholderText(_translate("MainWindow", "time"))
        self.label_28.setText(_translate("MainWindow", "Time :"))
        self.send_data_combobox_price.setItemText(0, _translate("MainWindow", "None"))
        self.send_data_combobox_price.setItemText(1, _translate("MainWindow", "Toman"))
        self.send_data_combobox_price.setItemText(2, _translate("MainWindow", "Rials"))
        self.send_data_combobox_price.setItemText(3, _translate("MainWindow", "Dollar"))
        self.send_data_combobox_price.setItemText(4, _translate("MainWindow", "Euro"))
        self.label_26.setText(_translate("MainWindow", "Tracking code :"))
        self.send_data_tracking_code.setPlaceholderText(_translate("MainWindow", "tracking code"))
        self.send_data_submit_btn.setText(_translate("MainWindow", "Submit"))
        self.send_data_clear_btn.setText(_translate("MainWindow", "Clear"))
        self.send_data_edit_btn.setText(_translate("MainWindow", "Edit"))
        item = self.tableWidget_get_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_get_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_get_data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_get_data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fullname"))
        item = self.tableWidget_get_data.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget_get_data.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Company"))
        item = self.tableWidget_get_data.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget_get_data.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_get_data.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget_get_data.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "State"))
        item = self.tableWidget_get_data.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Is_pay"))
        item = self.tableWidget_get_data.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Tracking code"))
        self.get_data_your_user_btn.setText(_translate("MainWindow", "Your user"))
        self.get_data_all_data_btn.setText(_translate("MainWindow", "All data"))
        self.label_29.setText(_translate("MainWindow", "Sort :"))
        self.label_30.setText(_translate("MainWindow", "ID :"))
        self.get_data_id_lineedit.setPlaceholderText(_translate("MainWindow", "Data ID"))
        self.get_data_refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.get_data_delete_btn.setText(_translate("MainWindow", "Delete data"))
        item = self.tableWidget_users.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_users.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_users.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fullname"))
        item = self.tableWidget_users.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_users.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget_users.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Type"))
        self.users_id_lineedit.setPlaceholderText(_translate("MainWindow", "User ID"))
        self.label_31.setText(_translate("MainWindow", "ID :"))
        self.users_refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.users_delete_btn.setText(_translate("MainWindow", "Delete data"))
        self.label_33.setText(_translate("MainWindow", "Title :"))
        self.feedback_title.setPlaceholderText(_translate("MainWindow", "title"))
        self.label_34.setText(_translate("MainWindow", "Username :"))
        self.feedback_username.setPlaceholderText(_translate("MainWindow", "username"))
        self.label_35.setText(_translate("MainWindow", "Feedback"))
        self.feedback_subject.setPlaceholderText(_translate("MainWindow", "subject"))
        self.label_36.setText(_translate("MainWindow", "Subject :"))
        self.label_37.setText(_translate("MainWindow", "Message :"))
        self.feedback_send_btn.setText(_translate("MainWindow", "Send"))
        self.feedback_clear_btn.setText(_translate("MainWindow", "Clear"))
        self.feedback_TextEdit.setPlaceholderText(_translate("MainWindow", "message"))
        item = self.tableWidget_feedback.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_feedback.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Username"))
        item = self.tableWidget_feedback.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableWidget_feedback.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Subject"))
        item = self.tableWidget_feedback.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Message"))
        self.feedbacks_id_lineedit.setPlaceholderText(_translate("MainWindow", "Feedback ID"))
        self.label_40.setText(_translate("MainWindow", "ID :"))
        self.feedbacks_refresh_btn.setText(_translate("MainWindow", "Refresh"))
        self.feedbacks_delete_btn.setText(_translate("MainWindow", "Delete data"))
        self.feedback_state_label_2.setText(_translate("MainWindow", "Please wait..."))
        self.label_41.setText(_translate("MainWindow", "Feedback Chart"))
        self.setting_btn.setText(_translate("MainWindow", " Setting"))
        self.profile_btn.setText(_translate("MainWindow", "Profile"))
        self.send_data_btn.setText(_translate("MainWindow", "Send data"))
        self.get_data_btn.setText(_translate("MainWindow", "Get data"))
        self.feedback_btn.setText(_translate("MainWindow", "Feedback"))
        self.users_btn.setText(_translate("MainWindow", "  Users"))
        self.log_out_btn.setText(_translate("MainWindow", "Log-out"))
        self.info_btn.setText(_translate("MainWindow", "  Info"))
        self.home_btn.setText(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
