# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 480)
        MainWindow.setMaximumSize(QtCore.QSize(780, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #536976, stop:1 #292E49);\n"
"border-radius:5px;")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 59, 780, 421))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(100, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(265, -20, 250, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(72)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(103, 220, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.login_username = QtWidgets.QLineEdit(self.page)
        self.login_username.setGeometry(QtCore.QRect(220, 170, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.login_username.setFont(font)
        self.login_username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.login_username.setObjectName("login_username")
        self.login_password = QtWidgets.QLineEdit(self.page)
        self.login_password.setGeometry(QtCore.QRect(220, 230, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.login_password.setFont(font)
        self.login_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password.setObjectName("login_password")
        self.state_login_label = QtWidgets.QLabel(self.page)
        self.state_login_label.setGeometry(QtCore.QRect(250, 350, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.state_login_label.setFont(font)
        self.state_login_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.state_login_label.setText("")
        self.state_login_label.setAlignment(QtCore.Qt.AlignCenter)
        self.state_login_label.setObjectName("state_login_label")
        self.check_btn = QtWidgets.QPushButton(self.page)
        self.check_btn.setGeometry(QtCore.QRect(340, 290, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.check_btn.setFont(font)
        self.check_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.check_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.check_btn.setIconSize(QtCore.QSize(30, 30))
        self.check_btn.setObjectName("check_btn")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.register_fullname = QtWidgets.QLineEdit(self.page_2)
        self.register_fullname.setGeometry(QtCore.QRect(230, 120, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.register_fullname.setFont(font)
        self.register_fullname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.register_fullname.setObjectName("register_fullname")
        self.register_submit_btn = QtWidgets.QPushButton(self.page_2)
        self.register_submit_btn.setGeometry(QtCore.QRect(360, 370, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.register_submit_btn.setFont(font)
        self.register_submit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.register_submit_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(113, 113, 113);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"background-color: rgb(89, 89, 89);\n"
"}\n"
"")
        self.register_submit_btn.setIconSize(QtCore.QSize(30, 30))
        self.register_submit_btn.setObjectName("register_submit_btn")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(110, 160, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(234, -34, 361, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(72)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(113, 260, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.register_password = QtWidgets.QLineEdit(self.page_2)
        self.register_password.setGeometry(QtCore.QRect(230, 270, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.register_password.setFont(font)
        self.register_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.register_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_password.setObjectName("register_password")
        self.register_username = QtWidgets.QLineEdit(self.page_2)
        self.register_username.setGeometry(QtCore.QRect(230, 170, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.register_username.setFont(font)
        self.register_username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.register_username.setObjectName("register_username")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(120, 110, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.register_re_password = QtWidgets.QLineEdit(self.page_2)
        self.register_re_password.setGeometry(QtCore.QRect(230, 320, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.register_re_password.setFont(font)
        self.register_re_password.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.register_re_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.register_re_password.setObjectName("register_re_password")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(66, 310, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.register_email = QtWidgets.QLineEdit(self.page_2)
        self.register_email.setGeometry(QtCore.QRect(230, 220, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.register_email.setFont(font)
        self.register_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;")
        self.register_email.setObjectName("register_email")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(144, 210, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: none;\n"
"color: rgb(0, 0, 0);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.state_register_label = QtWidgets.QLabel(self.page_2)
        self.state_register_label.setGeometry(QtCore.QRect(500, 360, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setItalic(True)
        self.state_register_label.setFont(font)
        self.state_register_label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.state_register_label.setText("")
        self.state_register_label.setAlignment(QtCore.Qt.AlignCenter)
        self.state_register_label.setObjectName("state_register_label")
        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setGeometry(QtCore.QRect(639, 123, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("background-color: rgb(144, 144, 144);\n"
"border-radius:0px;")
        self.checkBox.setObjectName("checkBox")
        self.stackedWidget.addWidget(self.page_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(661, -8, 121, 61))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.exit_btn = QtWidgets.QPushButton(self.frame)
        self.exit_btn.setGeometry(QtCore.QRect(66, 10, 51, 41))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(209, 0, 0);\n"
"border-radius:5px;\n"
"}")
        self.exit_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photo/icons8-close-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn.setIcon(icon)
        self.exit_btn.setIconSize(QtCore.QSize(30, 30))
        self.exit_btn.setObjectName("exit_btn")
        self.minimize_btn = QtWidgets.QPushButton(self.frame)
        self.minimize_btn.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.minimize_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(118, 118, 118);\n"
"border-radius:5px;\n"
"}")
        self.minimize_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photo/icons8-horizontal-line-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon1)
        self.minimize_btn.setIconSize(QtCore.QSize(30, 30))
        self.minimize_btn.setObjectName("minimize_btn")
        self.reg_log_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reg_log_btn.setGeometry(QtCore.QRect(1, 1, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.reg_log_btn.setFont(font)
        self.reg_log_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reg_log_btn.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: none;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(154, 154, 154);\n"
"border-radius:5px;\n"
"}\n"
"background-color: rgb(89, 89, 89);")
        self.reg_log_btn.setIconSize(QtCore.QSize(30, 30))
        self.reg_log_btn.setObjectName("reg_log_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.exit_btn.clicked.connect(MainWindow.close)
        self.minimize_btn.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Username :"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.label_3.setText(_translate("MainWindow", "Password :"))
        self.login_username.setPlaceholderText(_translate("MainWindow", "username"))
        self.login_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.check_btn.setText(_translate("MainWindow", "Check"))
        self.register_fullname.setPlaceholderText(_translate("MainWindow", "fullname"))
        self.register_submit_btn.setText(_translate("MainWindow", "Sign up"))
        self.label_4.setText(_translate("MainWindow", "Username :"))
        self.label_5.setText(_translate("MainWindow", "Register"))
        self.label_6.setText(_translate("MainWindow", "Password :"))
        self.register_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.register_username.setPlaceholderText(_translate("MainWindow", "username"))
        self.label_7.setText(_translate("MainWindow", "Fullname :"))
        self.register_re_password.setPlaceholderText(_translate("MainWindow", "password again"))
        self.label_8.setText(_translate("MainWindow", "Password-again :"))
        self.register_email.setPlaceholderText(_translate("MainWindow", "email"))
        self.label_9.setText(_translate("MainWindow", "Email :"))
        self.checkBox.setText(_translate("MainWindow", "Admin account"))
        self.reg_log_btn.setText(_translate("MainWindow", "Register"))

