# Generated by Django 4.0 on 2021-12-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('company', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=11)),
                ('time', models.CharField(max_length=14)),
                ('state', models.CharField(max_length=10)),
                ('is_pay', models.CharField(max_length=3)),
                ('tracking_code', models.CharField(max_length=100)),
            ],
        ),
    ]
